In [3]:
import numpy as np

# Problem 1 : Markov Chains

### a) States and Transition Probabilities (Transition Matrix)
   
   $$
   P = 
   \begin{bmatrix}
    & TT & ST & SS \\
   TT & \frac{1}{2} & \frac{1}{2} & 0 \\
   ST & \frac{1}{4} & \frac{1}{2} & \frac{1}{4} \\
   SS & 0 & \frac{1}{2} & \frac{1}{2}
   \end{bmatrix}
   $$


### b) Probabilities corresponding to different generations

**Generation 1**

Probability that one would be tall in height = $\frac{1}{4}$

Probability that one would be medium in height = $\frac{1}{2}$

Probability that one would be short in height = $\frac{1}{4}$

**Generation 2**

Probability that one would be tall in height = $\frac{1}{4}$

Probability that one would be medium in height = $\frac{1}{2}$

Probability that one would be short in height = $\frac{1}{4}$

**Generation 3**

Probability that one would be tall in height = $\frac{1}{4}$

Probability that one would be medium in height = $\frac{1}{2}$

Probability that one would be short in height = $\frac{1}{4}$


### c) Probabilities corresponding to different generations

For any generation, the probabilities would be same, i.e,

Probability that one would be tall in height = $\frac{1}{4}$

Probability that one would be medium in height = $\frac{1}{2}$

Probability that one would be short in height = $\frac{1}{4}$


# Problem 2 : Markov Reward Process

### a) States and Transition Probabilities (Transition Matrix)
   
   $$
   P = 
   \begin{bmatrix}
    & S & 1 & 3 & 5 & 6 & 7 & 8 & W \\
   S & 0 & \frac{1}{4} & \frac{1}{4} & 0 & 0 & \frac{1}{4} & \frac{1}{4} & 0 \\
   1 & 0 & 0 & \frac{1}{4} & \frac{1}{4} & 0 & \frac{1}{4} & \frac{1}{4} & 0 \\
   3 & 0 & 0 & 0 & \frac{1}{4} & \frac{1}{4} & \frac{1}{2} & 0 & 0 \\
   5 & 0 & 0 & \frac{1}{4} & 0 & \frac{1}{4} & \frac{1}{4} & \frac{1}{4} & 0 \\
   6 & 0 & 0 & \frac{1}{4} & 0 & 0 & \frac{1}{4} & \frac{1}{4} & \frac{1}{4} \\
   7 & 0 & 0 & \frac{1}{4} & 0 & 0 & \frac{1}{4} & \frac{1}{4} & \frac{1}{4} \\
   8 & 0 & 0 & \frac{1}{4} & 0 & 0 & 0 & \frac{1}{2} & \frac{1}{4} \\
   W & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
   \end{bmatrix}
   $$

#### b) Absorbing State

$W$ is the Absorbing State.

#### c) Expected Number of die throws

Reward Function, 
$
R = 
{
\begin{bmatrix}
-9 & -8 & -6 & -4 & -3 & -2 & -1 & 2 \\
\end{bmatrix}^{\;T}
}
$

Discount factor,
$
\gamma = 0.8
$

Bellman Equation,
$
V = (I - \gamma P)^{-1}R
$




In [12]:
R = np.array([-9,-8,-6,-4,-3,-2,-1,2]).reshape((8,1))
gamma = 0.8
I = np.identity(8)
P = np.array([[0,0.25,0.25,0,0,0.25,0.25,0],
              [0,0,0.25,0.25,0,0.25,0.25,0],
              [0,0,0,0.25,0.25,0.5,0,0],
              [0,0,0.25,0,0.25,0.25,0.25,0],
              [0,0,0.25,0,0,0.25,0.25,0.25],
              [0,0,0.25,0,0,0.25,0.25,0.25],
              [0,0,0.25,0,0,0,0.5,0.25],
              [0,0,0,0,0,0,0,1]])
inv = np.linalg.inv(I - gamma*P)
V = np.squeeze(np.matmul(inv,R).T)
print(V.T)

[-14.11333333 -12.16388889  -9.29166667  -7.41666667  -3.68055556
  -2.68055556  -1.43055556  10.        ]


Expected Number of Die throws = 10

# Problem 3 : Markov Decision Process

### a) Graphical Representation of the MDP

![MDP](MDP.jpg)

**HT** = Hill Top
**RD** = Rolling Down
**BH** = Bottom Hill
**DP** = Drive Probability
**NDP** = No Drive Probability

### b) Deteministic and Stochastic Policy

**Deterministic Policy** = LRV can always drive with a probability 1. <br>
**Stochastic Policy** = LRV can drive with a probability 0.5 and not drive with probability 0.5.

### c) Transition Matrix

**Deterministic Policy**
    $$
    P = 
    \begin{bmatrix}
    & Hill Top & Rolling Down & Bottom Hill \\
    Hill Top & 0.8 & 0.2 & 0 \\
    Rolling Down & 0.3 & 0.4 & 0.3 \\
    Bottom Hill & 0.7 & 0.3 & 0
    \end{bmatrix}
    $$
    
**Stochastic Policy**
    $$
    P = 
    \begin{bmatrix}
    & Hill Top & Rolling Down & Bottom Hill \\
    Hill Top & 0.7 & 0.3 & 0 \\
    Rolling Down & 0.15 & 0.25 & 0.6 \\
    Bottom Hill & 0.35 & 0.15 & 0.5
    \end{bmatrix}
    $$
    
    
### d) History Dependent Policy
The LRV can perform an action based on its current energy level. If the energy level is low, then it's better not to drive and amass as much energy as possible and then decide to take an action. For example, if it feels that it's energy levels are decreasing it can go up the hill and amass energy as it absorbs the maximum amount of energy at the top of the hill and then come down later for further exploration.

# Problem 4 : Policy Evaluation and Partial Ordering of Policies

### a) Policies

#### For Policy $\pi_1$ :
$
V^{\pi_1}(s = A) = 0.9[-10 + \gamma V^{\pi_1}(s = B)] + 0.1[-10 + \gamma V^{\pi_1}(s = C)] \\
V^{\pi_1}(s = B) = 0.9[-10 + 100\gamma] + 0.1[-10 + \gamma V^{\pi_1}(s = A)] \\
V^{\pi_1}(s = C) = 0.1[-10 + 100\gamma] + 0.9[-10 + \gamma V^{\pi_1}(s = A)] \\
V^{\pi_1}(s = D) = 100 \\
$

Solving the above equations and substituting $\gamma$ = 1, <br>
$
V^{\pi_1}(s = A) = 75.00 \\
V^{\pi_1}(s = B) = 87.50 \\
V^{\pi_1}(s = C) = 62.50 \\
V^{\pi_1}(s = D) = 100 \\
$


#### For Policy $\pi_2$ :
$
V^{\pi_2}(s = A) = 0.9[-10 + \gamma V^{\pi_2}(s = B)] + 0.1[-10 + \gamma V^{\pi_2}(s = C)] \\
V^{\pi_2}(s = B) = 0.1[-10 + 100\gamma] + 0.9[-10 + \gamma V^{\pi_2}(s = A)] \\
V^{\pi_2}(s = C) = 0.9[-10 + 100\gamma] + 0.1[-10 + \gamma V^{\pi_2}(s = A)] \\
V^{\pi_2}(s = D) = 100 \\
$

Solving the above equations and substituting $\gamma$ = 1, <br>
$
V^{\pi_2}(s = A) = 75.00 \\
V^{\pi_2}(s = B) = 62.50 \\
V^{\pi_2}(s = C) = 87.50 \\
V^{\pi_2}(s = D) = 100 \\
$


#### For Policy $\pi_3$ : 
$
V^{\pi_3}(s = A) = 0.42[-10 + \gamma V^{\pi_3}(s = B)] + 0.58[-10 + \gamma V^{\pi_3}(s = C)] \\
V^{\pi_3}(s = B) = 0.9[-10 + 100\gamma] + 0.1[-10 + \gamma V^{\pi_3}(s = A)] \\
V^{\pi_3}(s = C) = 0.9[-10 + 100\gamma] + 0.1[-10 + \gamma V^{\pi_3}(s = A)] \\
V^{\pi_3}(s = D) = 100 \\
$

Solving the above equations and substituting $\gamma$ = 1, <br>
$
V^{\pi_3}(s = A) = 77.78 \\
V^{\pi_3}(s = B) = 87.78 \\
V^{\pi_3}(s = C) = 87.78 \\
V^{\pi_3}(s = D) = 100 \\
$


# Problem 6 : Value Iteration


In [37]:
def calc_value_function(R,gamma,c):
    
    V = np.array([0,0,0,0,0,10+c],dtype = np.float32)
    epsilon = 1e-15
    max_iterations = 100
    
    for itr in range(max_iterations):
        
        prev_V = np.copy(V)
        for i in range(5):
            Q_s_a = []
            for a in range(2):
                if a == 0:
                    summation = V[max(i-1,0)]
                    Q_s_a.append(R[i]+gamma*summation)
                elif a == 1:
                    summation = V[i+1]
                    Q_s_a.append(R[i]+gamma*summation)
                    
            V[i] = np.max(Q_s_a)
            
        if np.sum(np.fabs(prev_V - V)) <= epsilon:
            print('Value iteration converged at iteration %d.'%(i+1))
            break
            
    return V            

### a) Optimal Policy and Optimal Value Function at $\gamma$ = 1

Optimal Policy, the agent can always take the action R, i.e, always go right at each state.

In [38]:
R = np.array([0,0,0,0,0,10])
V = calc_value_function(R,1,0)

print("Optimal Value Function :",np.around(V,decimals=2))

Value iteration converged at iteration 5.
Optimal Value Function : [10. 10. 10. 10. 10. 10.]


### b) Optimal Policy and Optimal Value Function at $\gamma$ = {0.9,0.5,0.1}

In [39]:
for gamma in [0.9,0.5,0.1]:
    V = calc_value_function(R,gamma,0)
    
    print("Gamma :",gamma)
    print(np.around(V,decimals=2))
    print('\n')

Value iteration converged at iteration 5.
Gamma : 0.9
[ 5.9   6.56  7.29  8.1   9.   10.  ]


Value iteration converged at iteration 5.
Gamma : 0.5
[ 0.31  0.62  1.25  2.5   5.   10.  ]


Value iteration converged at iteration 5.
Gamma : 0.1
[ 0.    0.    0.01  0.1   1.   10.  ]




We can use the same policy that was used above, i.e, moving right at each state.

### c) Adding a constant c to all rewards

In [40]:
for gamma in [0.9,0.5,0.1]:
    for c in [-15,-10,-5,5,10,15]:
        R = np.array([c,c,c,c,c,10+c])
        V = calc_value_function(R,gamma,c)

        print("Gamma :",gamma, " Constant c :",c)
        print(np.around(V,decimals=2))
        print('\n')
    

Value iteration converged at iteration 5.
Gamma : 0.9  Constant c : -15
[-64.38 -54.87 -44.3  -32.55 -19.5   -5.  ]


Value iteration converged at iteration 5.
Gamma : 0.9  Constant c : -10
[-40.95 -34.39 -27.1  -19.   -10.     0.  ]


Value iteration converged at iteration 5.
Gamma : 0.9  Constant c : -5
[-17.52 -13.91  -9.9   -5.45  -0.5    5.  ]


Value iteration converged at iteration 5.
Gamma : 0.9  Constant c : 5
[50. 50. 50. 50. 50. 15.]


Value iteration converged at iteration 5.
Gamma : 0.9  Constant c : 10
[100. 100. 100. 100. 100.  20.]


Value iteration converged at iteration 5.
Gamma : 0.9  Constant c : 15
[150. 150. 150. 150. 150.  25.]


Value iteration converged at iteration 5.
Gamma : 0.5  Constant c : -15
[-29.22 -28.44 -26.88 -23.75 -17.5   -5.  ]


Value iteration converged at iteration 5.
Gamma : 0.5  Constant c : -10
[-19.38 -18.75 -17.5  -15.   -10.     0.  ]


Value iteration converged at iteration 5.
Gamma : 0.5  Constant c : -5
[-9.53 -9.06 -8.12 -6.25 -2.5   

As we can see from the above results, as long as c is negative or zero it doesn't effect much and the optimal policy remains the same(moving right at each state). However for positive values of c, if gamma is small, then there is no problem and we can use the same optimal policy. However if gamma is large, the agent tries to explore the environment even more and in the process, the agent would not be able to reach the terminal state and moves away from it(we can see that the values decrease as we go from state s1 to s6.

### d) Relation between $V^{\pi}$ and $\hat{V}^{\pi}$

# Problem 7 : Effect of Noise and Discounting

In [42]:
def is_terminal_or_wall(i,j):
    return ((i == 1 and j == 1) or (i == 2 and j == 1) or (i == 2 and j == 2) or (i == 2 and j == 3) or (i == 2 and j == 4) or (i == 4))


In [43]:
def value_iteration(R,gamma,eeta):
    
    V = np.array([[0,0,0,0,0],
                  [0,0,0,0,0],
                  [0,0,1,0,10],
                  [0,0,0,0,0],
                  [-10,-10,-10,-10,-10]],dtype = np.float32)

    epsilon = 1e-10
    max_iterations = 100

    for itr in range(max_iterations):

        prev_V = np.copy(V)

        for i in range(5):
            for j in range(5):
                if not is_terminal_or_wall(i,j):
                    Q_s_a = []
                    for a in range(4):
                        if a == 0:
                            summation = (1-eeta)*V[i][max(j-1,0)]+(eeta/3)*V[max(i-1,0)][j]+(eeta/3)*V[min(i+1,4)][j]+(eeta/3)*V[i][min(j+1,4)]                        
                            Q_s_a.append((1-eeta)*R[i][j]+gamma*summation)
                        elif a == 1:
                            summation = (eeta/3)*V[i][max(j-1,0)]+(1-eeta)*V[max(i-1,0)][j]+(eeta/3)*V[min(i+1,4)][j]+(eeta/3)*V[i][min(j+1,4)]                        
                            Q_s_a.append((1-eeta)*R[i][j]+gamma*summation)
                        elif a == 2:
                            summation = (eeta/3)*V[i][max(j-1,0)]+(eeta/3)*V[max(i-1,0)][j]+(1-eeta)*V[min(i+1,4)][j]+(eeta/3)*V[i][min(j+1,4)]                        
                            Q_s_a.append((1-eeta)*R[i][j]+gamma*summation)
                        elif a == 3:
                            summation = (eeta/3)*V[i][max(j-1,0)]+(eeta/3)*V[max(i-1,0)][j]+(eeta/3)*V[min(i+1,4)][j]+(1-eeta)*V[i][min(j+1,4)]                        
                            Q_s_a.append((1-eeta)*R[i][j]+gamma*summation)

                    V[i][j] = np.max(Q_s_a)
    
        if np.sum(np.fabs(prev_V - V)) <= epsilon:
            print('Value iteration converged at iteration %d.'%(i+1))
            break
    
    return V

In [44]:
R = np.array([[0,0,0,0,0],
              [0,0,0,0,0],
              [0,0,1,0,10],
              [0,0,0,0,0],
              [-10,-10,-10,-10,-10]])

V = value_iteration(R,0.1,0.01)
print(np.around(V,decimals=2))

Value iteration converged at iteration 5.
[[  0.     0.     0.01   0.01   0.1 ]
 [  0.     0.     0.1    0.1    0.99]
 [  0.     0.     1.     0.    10.  ]
 [ -0.     0.01   0.1    0.09   0.99]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [117]:
V = value_iteration(R,0.8,0.185)
print(np.around(V,decimals=2))

[[  1.74   2.32   3.24   4.28   5.6 ]
 [  1.24   0.     3.62   5.23   7.42]
 [  0.86   0.     1.     0.    10.  ]
 [  0.14   0.9    2.13   3.88   6.54]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [116]:
V = value_iteration(R,0.69,0.185)
print(np.around(V,decimals=2))

[[  0.63   0.99   1.64   2.55   3.94]
 [  0.38   0.     2.19   3.7    6.21]
 [  0.21   0.     1.     0.    10.  ]
 [ -0.31   0.22   1.17   2.75   5.55]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [128]:
V = value_iteration(R,0.5,0.13)
print(np.around(V,decimals=2))

[[  0.1    0.21   0.46   0.98   2.09]
 [  0.04   0.     0.91   2.01   4.54]
 [  0.01   0.     1.     0.    10.  ]
 [ -0.22   0.01   0.52   1.65   4.26]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [133]:
V = value_iteration(R,0.2,0.7)
print(np.around(V,decimals=2))

[[ -0.     0.     0.     0.     0.04]
 [ -0.     0.     0.06   0.04   0.63]
 [ -0.03   0.     1.     0.    10.  ]
 [ -0.52  -0.51  -0.45  -0.48   0.12]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [145]:
V = value_iteration(R,0.1,0)
print(np.around(V,decimals=2))

[[  0.     0.     0.01   0.01   0.1 ]
 [  0.     0.     0.1    0.1    1.  ]
 [  0.     0.     1.     0.    10.  ]
 [  0.     0.01   0.1    0.1    1.  ]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [146]:
V = value_iteration(R,0.9,0)
print(np.around(V,decimals=2))

[[  5.31   5.9    6.56   7.29   8.1 ]
 [  4.78   0.     7.29   8.1    9.  ]
 [  5.31   0.     1.     0.    10.  ]
 [  5.9    6.56   7.29   8.1    9.  ]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [147]:
V = value_iteration(R,0.1,0.5)
print(np.around(V,decimals=2))

[[  0.     0.     0.     0.     0.03]
 [ -0.     0.     0.05   0.03   0.51]
 [ -0.     0.     1.     0.    10.  ]
 [ -0.17  -0.17  -0.12  -0.15   0.34]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [148]:
V = value_iteration(R,0.9,0.5)
print(np.around(V,decimals=2))

[[  1.27   1.75   2.89   4.07   5.35]
 [  0.67   0.     2.43   4.11   6.96]
 [ -0.02   0.     1.     0.    10.  ]
 [ -2.14  -2.03  -1.37  -0.13   3.51]
 [-10.   -10.   -10.   -10.   -10.  ]]


In [47]:
V = value_iteration(R,0.4,0.3)
print(np.around(V,decimals=2))

Value iteration converged at iteration 5.
[[  0.01   0.03   0.11   0.31   0.92]
 [  0.     0.     0.32   0.86   2.99]
 [ -0.02   0.     1.     0.    10.  ]
 [ -0.44  -0.42  -0.12   0.3    2.51]
 [-10.   -10.   -10.   -10.   -10.  ]]


From the above observations, <br>
**a)** If the noise factor is close to zero and the value of discount factor is also close to zero, then the agent prefers the close exit and risks the cliff. <br>
**b)** If the noise factor is close to zero and the value of discount factor is close to one, then the agent prefers the distant exit and risks the cliff. <br>
**c)** If the noise factor is close to one and the value of discount factor is close to zero, then the agent prefers the close exit and also avoids the cliff. <br>
**d)** If the noise factor is close to one and the value of discount factor is also close to one, then the agent prefers the distant exit and also avoids the cliff. <br>

# Problem 8 : Convergence Rate of Value Iteration

$
V_{k+1}(s) = max_{a} [ R_{ss'}^{a} + \gamma  {\sum}_{s' \in S} P_{ss'}^{a} V_{k}(s') ]
$

$
V_{*}(s) = max_{a} [ R_{ss'}^{a} + \gamma {\sum}_{s' \in S} P_{ss'}^{a} V_{*}(s') ]
$

$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \;  \leq | \;  \; \; [ R_{ss'}^{a} + \gamma  {\sum}_{s' \in S} P_{ss'}^{a} V_{k}(s') ] - [ R_{ss'}^{a} + \gamma  {\sum}_{s' \in S} P_{ss'}^{a} V_{*}(s') ] \; \; |
$


$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \; \leq | \;  \; \;  \gamma {\sum}_{s' \in S} P_{ss'}^{a} V_{k}(s')  -  \gamma  {\sum}_{s' \in S} P_{ss'}^{a} V_{*}(s') \; \; |
$


$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \; \leq \gamma \;  | \;  \; \;  {\sum}_{s' \in S} [ P_{ss'}^{a} V_{k}(s') -P_{ss'}^{a} V_{*}(s')] \; \; |
$

But $ {\sum}_{s' \in S} P_{ss'}^{a} = I $

$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \; \leq \gamma \;  | \;  \; \;  {\sum}_{s' \in S} P_{ss'}^{a}[V_{k}(s') -V_{*}(s')] \; \; |
$

$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \; \leq \gamma \;  | \;  \; \; [V_{k}(s') -V_{*}(s')] \; {\sum}_{s' \in S}P_{ss'}^{a}\; \; |
$

$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \; \leq \gamma \;  | \;  \; \; [V_{k}(s') -V_{*}(s')] \; I\; \; |
$

$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \; \leq \gamma \;  | \;  \; \; [V_{k}(s') -V_{*}(s')] \;  \; |
$

$
\implies | \; V_{k+1}(s) - V_{*}(s) \; | \; \leq \gamma \;  | \;  \; \; [V_{k}(s') -V_{*}(s')] \;  \; | \leq \gamma \; \gamma \;  | \;  \; \; [V_{k-1}(s') -V_{*}(s')] \;  \; |
$

$
Similarly, | \; V_{k+1}(s) - V_{*}(s) \; |_\infty \; \leq \gamma^{k} \;  | \;  \; \;V_{1}(s') -V_{*}(s')\;  \; |
$